//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGroup.RequestResponse.Client.ProxyCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestDTOOfClienteModelXEcaxEXn", Namespace="http://schemas.datacontract.org/2004/07/LGroup.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class RequestDTOOfClienteModelXEcaxEXn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LGroup.RequestResponse.Client.ProxyCliente.ClienteModel NovoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioLogadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LGroup.RequestResponse.Client.ProxyCliente.ClienteModel NovoCliente {
            get {
                return this.NovoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NovoClienteField, value) != true)) {
                    this.NovoClienteField = value;
                    this.RaisePropertyChanged("NovoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioLogado {
            get {
                return this.UsuarioLogadoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioLogadoField, value) != true)) {
                    this.UsuarioLogadoField = value;
                    this.RaisePropertyChanged("UsuarioLogado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteModel", Namespace="http://schemas.datacontract.org/2004/07/LGroup.Model")]
    [System.SerializableAttribute()]
    public partial class ClienteModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDTOOfClienteModelXEcaxEXn", Namespace="http://schemas.datacontract.org/2004/07/LGroup.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseDTOOfClienteModelXEcaxEXn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataExecucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LGroup.RequestResponse.Client.ProxyCliente.ClienteModel[] ListModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemProcessamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TempoExecucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LGroup.RequestResponse.Client.ProxyCliente.TipoMensagem TipoMensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataExecucao {
            get {
                return this.DataExecucaoField;
            }
            set {
                if ((this.DataExecucaoField.Equals(value) != true)) {
                    this.DataExecucaoField = value;
                    this.RaisePropertyChanged("DataExecucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LGroup.RequestResponse.Client.ProxyCliente.ClienteModel[] ListModel {
            get {
                return this.ListModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ListModelField, value) != true)) {
                    this.ListModelField = value;
                    this.RaisePropertyChanged("ListModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemProcessamento {
            get {
                return this.MensagemProcessamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemProcessamentoField, value) != true)) {
                    this.MensagemProcessamentoField = value;
                    this.RaisePropertyChanged("MensagemProcessamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TempoExecucao {
            get {
                return this.TempoExecucaoField;
            }
            set {
                if ((this.TempoExecucaoField.Equals(value) != true)) {
                    this.TempoExecucaoField = value;
                    this.RaisePropertyChanged("TempoExecucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LGroup.RequestResponse.Client.ProxyCliente.TipoMensagem TipoMensagem {
            get {
                return this.TipoMensagemField;
            }
            set {
                if ((this.TipoMensagemField.Equals(value) != true)) {
                    this.TipoMensagemField = value;
                    this.RaisePropertyChanged("TipoMensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoMensagem", Namespace="http://schemas.datacontract.org/2004/07/LGroup.Global.Enum")]
    public enum TipoMensagem : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aviso = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Cadastrar", ReplyAction="http://tempuri.org/IClienteService/CadastrarResponse")]
        LGroup.RequestResponse.Client.ProxyCliente.ResponseDTOOfClienteModelXEcaxEXn Cadastrar(LGroup.RequestResponse.Client.ProxyCliente.RequestDTOOfClienteModelXEcaxEXn pedido_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Cadastrar", ReplyAction="http://tempuri.org/IClienteService/CadastrarResponse")]
        System.Threading.Tasks.Task<LGroup.RequestResponse.Client.ProxyCliente.ResponseDTOOfClienteModelXEcaxEXn> CadastrarAsync(LGroup.RequestResponse.Client.ProxyCliente.RequestDTOOfClienteModelXEcaxEXn pedido_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Listar", ReplyAction="http://tempuri.org/IClienteService/ListarResponse")]
        LGroup.RequestResponse.Client.ProxyCliente.ResponseDTOOfClienteModelXEcaxEXn Listar(LGroup.RequestResponse.Client.ProxyCliente.RequestDTOOfClienteModelXEcaxEXn pedido_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Listar", ReplyAction="http://tempuri.org/IClienteService/ListarResponse")]
        System.Threading.Tasks.Task<LGroup.RequestResponse.Client.ProxyCliente.ResponseDTOOfClienteModelXEcaxEXn> ListarAsync(LGroup.RequestResponse.Client.ProxyCliente.RequestDTOOfClienteModelXEcaxEXn pedido_);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : LGroup.RequestResponse.Client.ProxyCliente.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<LGroup.RequestResponse.Client.ProxyCliente.IClienteService>, LGroup.RequestResponse.Client.ProxyCliente.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LGroup.RequestResponse.Client.ProxyCliente.ResponseDTOOfClienteModelXEcaxEXn Cadastrar(LGroup.RequestResponse.Client.ProxyCliente.RequestDTOOfClienteModelXEcaxEXn pedido_) {
            return base.Channel.Cadastrar(pedido_);
        }
        
        public System.Threading.Tasks.Task<LGroup.RequestResponse.Client.ProxyCliente.ResponseDTOOfClienteModelXEcaxEXn> CadastrarAsync(LGroup.RequestResponse.Client.ProxyCliente.RequestDTOOfClienteModelXEcaxEXn pedido_) {
            return base.Channel.CadastrarAsync(pedido_);
        }
        
        public LGroup.RequestResponse.Client.ProxyCliente.ResponseDTOOfClienteModelXEcaxEXn Listar(LGroup.RequestResponse.Client.ProxyCliente.RequestDTOOfClienteModelXEcaxEXn pedido_) {
            return base.Channel.Listar(pedido_);
        }
        
        public System.Threading.Tasks.Task<LGroup.RequestResponse.Client.ProxyCliente.ResponseDTOOfClienteModelXEcaxEXn> ListarAsync(LGroup.RequestResponse.Client.ProxyCliente.RequestDTOOfClienteModelXEcaxEXn pedido_) {
            return base.Channel.ListarAsync(pedido_);
        }
    }
}
